# Generated by Django 4.2.5 on 2024-04-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='Course',
        ),
    ]
